/*
 * Test case for BRE
 *
 * Service
 *
 * API version: 1.0.0
 * Contact: gk@rekunov.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Content struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Body string `json:"body"`
}
