openapi: 3.0.0
info:
  title: Test case for BRE
  description: Service
  contact:
    email: gk@rekunov.ru
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: /
paths:
  /content:
    post:
      summary: add content
      description: Adds an content to database
      operationId: addContent
      requestBody:
        description: Content to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Content'
      responses:
        "201":
          description: content added
        "400":
          description: "invalid input, object invalid"
        "409":
          description: an existing item already exists
components:
  schemas:
    Content:
      required:
      - body
      - id
      - name
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Widget Adapter
        body:
          type: string
          example: "{}"
