/*
 * Test case for BRE
 *
 * Service
 *
 * API version: 1.0.0
 * Contact: gk@rekunov.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	sw "github.com/xpoh/BRE-test/cmd/go"
	"log"
	"net/http"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
